### ISSUE TITLE
Time for a refresh?

### ISSUE THREAD

**Issue by domgiles** [dastultz/micropython-pyb#1]
Hi... It's a useful little lib for PyCharm etc.

Have you thought about a refresh? There's some new classes etc.

Appreciate your efforts 

Dom

**Comment by dastultz** [comment]
Thanks for your interest, Dom, glad to see someone using it. I'll take a look the latest version of pyb.

**Comment by dastultz** [comment]
Updated as per latest documentation. I don't quite understand the `ADCAll` Object so didn't include it.

Let me know if you see something I missed.

Closing.
